import type { NextPage } from 'next';
import Head from 'next/head';
import { HomeView } from '@/views/Home';

const Page: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <HomeView />
  </>
);


export default Page;
